# Generated by Django 5.0.2 on 2024-03-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='no-image.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
