# Generated by Django 5.0.2 on 2024-03-05 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrabbit',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='subrabbit',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subrabbit',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
