# Generated by Django 5.0.2 on 2024-03-12 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_subrabbit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrabbit',
            name='name',
            field=models.CharField(max_length=21, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(21)]),
        ),
    ]
