# Generated by Django 5.0.2 on 2024-06-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_subrabbit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
