name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements_workflow.txt
    - name: Run Tests
      run: |
        echo "Running tests..."

  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest

    steps: 
      - name: Deploy to production
        env: 
          deploy_url:  ${{  secrets.RENDER_DEPLOY_HOOK_URL  }} 
        run: |  
          curl \"$deploy_url\"
